# Autogenerated wrapper script for libCppInterOpExtra_jll for x86_64-w64-mingw32-cxx11-llvm_version+17.asserts
export libCppInterOpExtra

using Clang_jll
JLLWrappers.@generate_wrapper_header("libCppInterOpExtra")
JLLWrappers.@declare_library_product(libCppInterOpExtra, "libCppInterOpExtra.dll")
function __init__()
    JLLWrappers.@generate_init_header(Clang_jll)
    JLLWrappers.@init_library_product(
        libCppInterOpExtra,
        "bin\\libCppInterOpExtra.dll",
        nothing,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
