# Autogenerated wrapper script for libCppInterOpExtra_jll for x86_64-apple-darwin-llvm_version+17
export libCppInterOpExtra

using Clang_jll
JLLWrappers.@generate_wrapper_header("libCppInterOpExtra")
JLLWrappers.@declare_library_product(libCppInterOpExtra, "@rpath/libCppInterOpExtra.dylib")
function __init__()
    JLLWrappers.@generate_init_header(Clang_jll)
    JLLWrappers.@init_library_product(
        libCppInterOpExtra,
        "lib/libCppInterOpExtra.dylib",
        nothing,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
